export type { WallpaperOption } from "./types";
export { DeviceInfoSection } from "./device-info-section";
export { AccountSection } from "./account-section";
export { WallpaperSection } from "./wallpaper-section";
export { WifiSection } from "./wifi-section";
export { LanguageSection } from "./language-section";
export { FirewallSection } from "./firewall-section";
export { AdvancedSettingsSection, AdvancedSettingsContent } from "./advanced-settings-section";
export { TroubleshootSection } from "./troubleshoot-section";
export { StorageSection } from "./storage-section";
export { UpdateSection } from "./update-section";
export { NetworkDevicesSection } from "./network-devices-section";
export { SystemDetailsCard } from "./system-details-card";
